# Generated by Django 5.2.2 on 2025-06-06 08:27

import concurrency.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('value', models.IntegerField(default=0)),
                ('version', concurrency.fields.IntegerVersionField(default=0, help_text='record revision number')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
